# Overview

This Rmd provides quick end-to-end examples using the default `harbinger()` pipeline on several datasets (nonstationarity, global temperature monthly/yearly, multidimensional, and Seattle temperatures). For each dataset we: fit the default pipeline, run detection, and plot detections over the series.

```{r}
# Install Harbinger (only once, if needed)
#install.packages("harbinger")
```

```{r}
# Load required packages
library(daltoolbox)
library(harbinger) 
```

```{r}
# Load example datasets bundled with harbinger
data(examples_harbinger)
model <- harbinger()
```

```{r}
# Example: nonstationarity time series
dataset <- examples_harbinger$nonstationarity
model <- fit(model, dataset$serie)
detection <- detect(model, dataset$serie)
har_plot(model, dataset$serie, detection, dataset$event)

```

```{r}
# Example: global temperature (yearly)
dataset <- examples_harbinger$global_temperature_yearly
model <- fit(model, dataset$serie)
detection <- detect(model, dataset$serie)
har_plot(model, dataset$serie, detection, dataset$event)

```

```{r}
# Example: global temperature (monthly)
dataset <- examples_harbinger$global_temperature_monthly
model <- fit(model, dataset$serie)
detection <- detect(model, dataset$serie)
har_plot(model, dataset$serie, detection, dataset$event)

```

```{r}
# Example: multidimensional time series
dataset <- examples_harbinger$multidimensional
model <- fit(model, dataset$serie)
detection <- detect(model, dataset$serie)
har_plot(model, dataset$serie, detection, dataset$event)


model <- fit(model, dataset$x)
detection <- detect(model, dataset$x)
har_plot(model, dataset$x, detection, dataset$event)

```

```{r}
# Example: Seattle weekly temperature time series
dataset <- examples_harbinger$seattle_week
model <- fit(model, dataset$serie)
detection <- detect(model, dataset$serie)
har_plot(model, dataset$serie, detection, dataset$event)

```

```{r}
# Example: Seattle daily temperature time series
dataset <- examples_harbinger$seattle_daily
model <- fit(model, dataset$serie)
detection <- detect(model, dataset$serie)
har_plot(model, dataset$serie, detection, dataset$event)

```

