# DAL Library
# version 2.1

# depends dal_transform.R

### Normalization

# normalize normalization
#'@title Normalization
#'@description The normalize() function in the DAL package performs a normalization on the input data so that each feature (column) has zero mean and unit variance. Normalizing the data is a common preprocessing step in machine learning, particularly when using algorithms that are sensitive to the scale of the input features. The resulting normalized object is returned with the "normalize" class added to it.
#'@details The normalize() function subtracts the mean value of each feature from the data and then divides each feature by its standard deviation to ensure that all features have the same scale. This is done to make sure that the contribution of each feature to the analysis is balanced and no single feature dominates the analysis. The resulting object is returned with the "normalize" class added to it.
#'
#'@return
#'@examples
#'@export
normalize <- function() {
  obj <- dal_transform()
  class(obj) <- append("normalize", class(obj))
  return(obj)
}


# min-max normalization
#'@title Min-Max Normalization
#'@description The minmax() function performs Min-Max normalization on the data using the normalize() function from the DAL package and adds the "minmax" class to the resulting object. Min-Max normalization transforms the data to a specific range of values. Specifically, the function maps the smallest input value to 0 and the largest input value to 1, and transforms all other values to a range between 0 and 1. This normalization is useful when we want to put all variables on the same scale and avoid larger values dominating the analysis.
#'@details The minmax() function calls the normalize() function from the DAL package to normalize the data and then adds the "minmax" class to the resulting object. The "minmax" class is added so that users can easily distinguish between different types of normalizations applied to the data.
#'
#'@return
#'@examples
#'@export
minmax <- function() {
  obj <- normalize()
  class(obj) <- append("minmax", class(obj))
  return(obj)
}

#'@title Fit MinMax
#'@description The fit.minmax() function in the DAL package is used to fit a min-max normalization to the input data. Min-max normalization scales the input data so that all feature values are within the range of 0 and 1. This is done by subtracting the minimum value of each feature from all values of that feature and then dividing by the range of that feature. The resulting normalization parameters are saved in the input object, and the modified object is returned.
#'@details The fit.minmax() function takes two arguments: obj, which is an object of class minmax returned by the minmax() function, and data, which is a data frame containing the input data to be normalized. The function first creates a data frame minmax with the same number of columns as data and sets the values of the first row to 1 for columns that contain numeric data and 0 otherwise. The second and third rows of minmax are set to NA initially. The column and row names of minmax are set to the column names and "numeric", "max", and "min", respectively.
#'
#'@return
#'@examples
#'@export
fit.minmax <- function(obj, data) {
  minmax = data.frame(t(ifelse(sapply(data, is.numeric), 1, 0)))
  minmax = rbind(minmax, rep(NA, ncol(minmax)))
  minmax = rbind(minmax, rep(NA, ncol(minmax)))
  colnames(minmax) = colnames(data)
  rownames(minmax) = c("numeric", "max", "min")
  for (j in colnames(minmax)[minmax["numeric",]==1]) {
    minmax["min",j] <- min(data[,j], na.rm=TRUE)
    minmax["max",j] <- max(data[,j], na.rm=TRUE)
  }
  obj$norm.set <- minmax
  return(obj)
}


#'@title Transform MinMax
#'@description The transform() function in the DAL package transforms the input data based on the normalization set stored in the object generated by the fit.minmax() function. The function applies the min-max scaling method on the input data to bring the values of each feature (column) within the range of 0 to 1, based on the minimum and maximum values of the feature in the normalization set. If the minimum and maximum values of the feature are the same, the function sets the values in that feature to 0.
#'@details The transform() function takes the normalization set stored in the input object and applies it to the input data. The normalization set contains the minimum and maximum values of each feature in the original data set. The function applies the min-max scaling method to each feature in the input data by subtracting the minimum value of the feature from all values in that feature and dividing the result by the difference between the maximum and minimum values of that feature in the normalization set. If the minimum and maximum values of the feature are the same, the function sets the values in that feature to 0.
#'
#'@return
#'@examples
#'@export
transform.minmax <- function(obj, data) {
  minmax <- obj$norm.set
  for (j in colnames(minmax)[minmax["numeric",]==1]) {
    if ((minmax["max", j] != minmax["min", j])) {
      data[,j] <- (data[,j] - minmax["min", j]) / (minmax["max", j] - minmax["min", j])
    }
    else {
      data[,j] <- 0
    }
  }
  return (data)
}

#'@title Inverse Transform MinMax
#'@description The inverse_transform() function in the DAL package is used to transform normalized data back to its original scale. It takes as input a DAL object with a "minmax" class and a data frame containing the normalized data. The function applies the inverse min-max scaling formula to each column of the data frame using the maximum and minimum values stored in the DAL object. The resulting data frame is returned with the original scale of the data restored.
#'@details The inverse_transform() function is useful when the original scale of the data needs to be restored for interpretation or visualization purposes after training a model on normalized data. It should be noted that the restored data may not have the same exact scale as the original data due to rounding errors that occur during the normalization process.
#'
#'@return
#'@examples
#'@export
inverse_transform.minmax <- function(obj, data) {
  minmax <- obj$norm.set
  for (j in colnames(minmax)[minmax["numeric",]==1]) {
    if ((minmax["max", j] != minmax["min", j])) {
      data[,j] <- data[,j] * (minmax["max", j] - minmax["min", j]) + minmax["min", j]
    }
    else {
      data[,j] <- minmax["max", j]
    }
  }
  return (data)
}

# z-score normalization
#'@title Z-score Normalization
#'@description The zscore() function in the DAL package performs a normalization on the input data so that each feature (column) has zero mean and standard deviation of nsd. Normalizing the data is a common preprocessing step in machine learning, particularly when using algorithms that are sensitive to the scale of the input features. The resulting zscore normalized object is returned with the "zscore" class added to it.
#'@details The function takes two optional arguments:
#'@details nmean: A numeric value that specifies the desired mean of the normalized data. The default value is 0.
#'@details nsd: A numeric value that specifies the desired standard deviation of the normalized data. The default value is 1.
#'
#'@param nmean
#'@param nsd
#'@return
#'@examples
#'@export
zscore <- function(nmean=0, nsd=1) {
  obj <- normalize()
  obj$nmean <- nmean
  obj$nsd <- nsd
  class(obj) <- append("zscore", class(obj))
  return(obj)
}


#'@title Fit Z-score
#'@description The fit() function in the DAL package is used to fit a Z-score normalization object to a given data set. The function calculates the mean and standard deviation of each numeric column of the data set and stores these values in a data frame that is added to the normalization object with the "zscore" class. This object can then be used to transform new data to the same normalized scale.
#'@details The fit() function takes two arguments:
#'@details obj: A DAL object with the "zscore" class.
#'@details data: A data frame containing the data to be normalized.
#'
#'@return The function returns the input normalization object with the "norm.set" slot updated to contain the mean and standard deviation of each numeric column in the input data frame.
#'@examples
#'@export
fit.zscore <- function(obj, data) {
  nmean <- obj$nmean
  nsd <- obj$nsd
  zscore <- data.frame(t(ifelse(sapply(data, is.numeric), 1, 0)))
  zscore <- rbind(zscore, rep(NA, ncol(zscore)))
  zscore <- rbind(zscore, rep(NA, ncol(zscore)))
  zscore <- rbind(zscore, rep(NA, ncol(zscore)))
  zscore <- rbind(zscore, rep(NA, ncol(zscore)))
  colnames(zscore) <- colnames(data)
  rownames(zscore) <- c("numeric", "mean", "sd","nmean", "nsd")
  for (j in colnames(zscore)[zscore["numeric",]==1]) {
    zscore["mean",j] <- mean(data[,j], na.rm=TRUE)
    zscore["sd",j] <- sd(data[,j], na.rm=TRUE)
    zscore["nmean",j] <- nmean
    zscore["nsd",j] <- nsd
  }
  obj$norm.set <- zscore

  return(obj)
}

#'@title Transform Z-score
#'@description The function fit.zscore() in the DAL package calculates the mean and standard deviation of each numeric feature in the input data and transforms the data to have zero mean and unit standard deviation using the z-score normalization method. The resulting normalized object is returned with the "zscore" class added to it.
#'@details The fit.zscore() function takes an object created by the zscore() function and an input data frame. It first creates an empty data frame to store the z-score normalization parameters, such as mean and standard deviation, for each feature. Then, for each numeric feature in the input data frame, it calculates the mean and standard deviation and stores them in the corresponding rows of the parameter data frame. Finally, it normalizes the input data using the z-score normalization method and returns the normalized object with the "zscore" class.
#'
#'@return
#'@examples
#'@export
transform.zscore <- function(obj, data) {
  zscore <- obj$norm.set
  for (j in colnames(zscore)[zscore["numeric",]==1]) {
    if ((zscore["sd", j]) > 0) {
      data[,j] <- (data[,j] - zscore["mean", j]) / zscore["sd", j] * zscore["nsd", j] + zscore["nmean", j]
    }
    else {
      data[,j] <- obj$nmean
    }
  }
  return (data)
}

#'@title Inverse Transform Zscore
#'@description The inverse_transform() function is a part of the DALTOOLBOX  package in R, which is used to perform an inverse transformation on the normalized data that was transformed using the Z-score normalization method. The function takes two arguments - an object obj that contains the Z-score normalization parameters, and a dataset data that needs to be transformed back to its original scale. The function applies the inverse transformation formula to each numeric column in the data and returns the transformed dataset.
#'@details The inverse_transform() function takes two arguments - an object obj that was obtained by calling the zscore() function, and a dataset data that needs to be transformed back to its original scale. The function first extracts the normalization parameters - mean, standard deviation, normalized mean, and normalized standard deviation from the obj object. Then, the function applies the inverse transformation formula to each numeric column in the data using these parameters. If the standard deviation is zero for a column, the function sets the column values to the normalized mean.
#'
#'@return
#'@examples
#'@export
inverse_transform.zscore <- function(obj, data) {
  zscore <- obj$norm.set
  for (j in colnames(zscore)[zscore["numeric",]==1]) {
    if ((zscore["sd", j]) > 0) {
      data[,j] <- (data[,j] - zscore["nmean", j]) / zscore["nsd", j] * zscore["sd", j] + zscore["mean", j]
    }
    else {
      data[,j] <- zscore["nmean", j]
    }
  }
  return (data)
}
