# DAL Library
# version 2.1

# depends dal_transform.R
# depends ts_data.R
# depends ts_regression.R
# depends ts_preprocessing.R

# class ts_elm
# loadlibrary("elmNNRcpp")

### ts_augment
#'@title Time Series Extreme Learning Machine (ELM)
#'@description Machine learning technique used for time series forecasting.
#' ELM is a type of feedforward neural network that uses a single hidden layer
#' of randomly generated neurons.
#'@details
#'
#'@param preprocess
#'@param input_size
#'@param nhid
#'@param actfun string: defines the type to use, possible values: 'sig',
#' 'radbas', 'tribas', 'relu', 'purelin' (default).
#'@return a `ts_elm` object.
#'@examples
#'@export
ts_elm <- function(preprocess=NA, input_size=NA, nhid=NA, actfun='purelin') {
  obj <- tsreg_sw(preprocess, input_size)
  if (is.na(nhid))
    nhid <- input_size/3
  #nhid=c(3:8)
  obj$nhid <- nhid
  #actfun = c('sig', 'radbas', 'tribas', 'relu', 'purelin')
  obj$actfun <- as.character(actfun)

  class(obj) <- append("ts_elm", class(obj))
  return(obj)
}

#'@title Set specific parameters of a ts_elm object
#'
#'@description This function takes two arguments: obj, which is an object of the ts_elm class, and params, which is a list of parameters to be updated
#'
#'@details The function checks if the nhid parameter is present in the params parameter list. If the nhid parameter is present, the nhid value in the obj object is updated with the nhid value in params
#'
#'@param obj
#'@param params
#'
#'@return The object obj updated with the new parameters
#'@examples
#'@export
set_params.ts_elm <- function(obj, params) {
  if (!is.null(params$nhid))
    obj$nhid <- params$nhid
  if (!is.null(params$actfun))
    obj$actfun <- as.character(params$actfun)
  return(obj)
}

#'@import elmNNRcpp
#'
#'@title Train an ELM (Extreme Learning Machine) model
#'
#'@description This function takes three arguments: obj, which is an object of the ts_elm class, x, which is an array with the predictor variables, and y, which is a vector with the response variable. After training, the resulting ELM model is stored in the obj object using the model attribute
#'
#'@details The function uses the implementation of the elmNNRcpp library to train the ELM model
#'
#'@param obj
#'@param x
#'@param y
#'
#'@return The obj object updated with the trained model
#'@examples
#'@export
do_fit.ts_elm <- function(obj, x, y) {
  obj$model <- elmNNRcpp::elm_train(x, y, nhid = obj$nhid, actfun = obj$actfun, init_weights = "uniform_positive", bias = FALSE, verbose = FALSE)
  return(obj)
}

#'@import elmNNRcpp
#'@title Make predictions using a previously trained ELM model
#'@description This function takes obj and x as arguments
#'@details The function first checks whether the argument x is a data.frame object and, if so, converts it to a matrix using the as.matrix function. Then the function uses the implementation of the elmNNRcpp library to make the predictions
#'
#'@param obj
#'@param x
#'
#'@return A numerical object containing the predictions generated by the ELM model for the predictor variables x.
#'@examples
#'@export
do_predict.ts_elm <- function(obj, x) {
  if (is.data.frame(x))
    x <- as.matrix(x)
  prediction <- elmNNRcpp::elm_predict(obj$model, x)
  return(prediction)
}
